'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {chromium}=require('playwright');
const {createLocalApp}=require('./helpers/local-app');

(async()=>{
 const app=await createLocalApp();let browser;
 const output=path.resolve(process.env.NP_TEST_OUTPUT||'test-results/browser');fs.mkdirSync(output,{recursive:true});
 const observations=[];
 try{
  browser=await chromium.launch({headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];
  page.on('pageerror',e=>errors.push(e.stack||e.message));
  await page.route('https://**/*',route=>route.abort());
  // Old staff caches are purged; historical combat recovery has its own regression tests.
  await page.addInitScript(()=>{localStorage.setItem('np_spawn_lab_staff',JSON.stringify({private:true}));});
  await page.goto(app.origin,{waitUntil:'load'});await page.waitForTimeout(2200);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.screenshot({path:path.join(output,'home-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});await page.waitForTimeout(300);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.screenshot({path:path.join(output,'home-mobile.png'),fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.evaluate(()=>showScreen('s-login'));await page.waitForTimeout(1500);
  assert.equal(await page.locator('#login-id').evaluate(e=>e.labels.length),1);assert.equal(await page.locator('#login-pass').evaluate(e=>e.labels.length),1);
  await page.locator('#login-id').fill('Alice');await page.locator('#login-pass').fill('Alice-audit-123!');
  await page.locator('button[onclick="loginUnified()"]').click();await page.waitForFunction(()=>window.CU&&CU.role==='joueur',null,{timeout:15000});
  await page.waitForFunction(()=>!document.getElementById('login-transition-overlay').classList.contains('active')&&getComputedStyle(document.getElementById('lto-flash')).opacity==='0');
  await page.evaluate(async()=>{await forceOpenOwnProfile();renderJournalFiche(gpid('p_alice'));window.__testNotices=[];const previous=window.notif;window.notif=function(message,type){window.__testNotices.push({message,type});return previous.apply(this,arguments);};});
  await page.evaluate(async()=>{document.getElementById('journal-fiche-text').value='Journal navigateur conservé';await saveJournalFiche('p_alice');});
  assert.equal((await app.read('players')).value.find(p=>p.id==='p_alice').journal,'Journal navigateur conservé');
  assert.ok(await page.evaluate(()=>__testNotices.some(n=>n.type==='ok')));
  observations.push('Real login and journal save through both production handlers');
  const changed=(await app.read('players')).value;changed.find(p=>p.id==='p_bob').journal='Parallel edit';await app.seed('players',changed);
  await page.evaluate(async()=>{__testNotices=[];document.getElementById('journal-fiche-text').value='Stale draft';await saveJournalFiche('p_alice');});
  assert.equal((await app.read('players')).value.find(p=>p.id==='p_alice').journal,'Journal navigateur conservé');
  assert.equal(await page.evaluate(()=>__testNotices.some(n=>n.type==='ok')),false);
  observations.push('Conflicting journal save shows no success and preserves remote data');
  const xss=await page.evaluate(()=>{const malicious='x" onerror="window.__NP_AUDIT_XSS=1" data-a="';_dbCache.players=[_normalizePlayerRecord({id:'p_alice',name:'Alice',avatar:malicious},0)];updateHdrProfile();return _dbCache.players[0].avatar;});
  await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>!!window.__NP_AUDIT_XSS),false);assert.equal(xss,'');
  observations.push('Legacy malicious avatar does not execute');
  await page.evaluate(async()=>{await _loadSessionBundle();await saveCombatArchives([{id:'browser-arc',name:'Browser combat',log:['turn stored'],fighters:[],savedAt:Date.now()}],'Alice');});
  const rec=await app.read('combat_arc_rec_Alice__browser-arc');assert.equal(rec.value.id,'browser-arc');assert.deepEqual(rec.value.log,['turn stored']);
  assert.equal(await page.evaluate(()=>Object.keys(localStorage).some(k=>/combat_arc|spawn_lab_staff/.test(k))),false);
  observations.push('Detailed archive persisted and private data absent from localStorage');
  await page.screenshot({path:path.join(output,'player-desktop.png'),fullPage:true});
  await page.evaluate(async()=>{await saveCombatArchives(Array.from({length:55},(_,i)=>({id:'archive-'+i,name:'Combat '+i,savedAt:Date.now()+i,fighters:[],log:['detail-'+i]})),'Alice');});
  assert.equal((await app.read('combat_arc_idx_Alice')).value.length,55);
  assert.equal((await app.read('combat_arc_Alice')).value.length,50);
  await page.reload();await page.waitForFunction(()=>window.CU&&CU.role==='joueur');
  const oldDetail=await page.evaluate(async()=>{const list=getCombatArchives();const meta=list.find(a=>a.id==='archive-0');return combatArchiveFetchRecord('Alice','archive-0',meta);});
  assert.equal(oldDetail.id,'archive-0');assert.deepEqual(oldDetail.log,['detail-0']);
  observations.push('55 archive records remain readable after reload, beyond the compatibility list');
  const beforeFailure=await app.read('combat_arc_idx_Alice');
  await page.route('**/.netlify/functions/db',async route=>{const body=route.request().postDataJSON();if(body.action==='set'&&body.key==='combat_arc_rec_Alice__fail-detail')return route.fulfill({status:503,contentType:'application/json',body:'{"ok":false,"error":"simulated write failure"}'});return route.continue();});
  const refused=await page.evaluate(async()=>{try{await saveCombatArchives([{id:'fail-detail',name:'Failure',fighters:[],savedAt:Date.now()}],'Alice');return false;}catch(e){return true;}});
  assert.equal(refused,true);assert.equal((await app.read('combat_arc_idx_Alice')).version,beforeFailure.version);
  observations.push('Failure to persist a detail cannot replace the archive index');
  const cookies=await page.context().cookies();const oldCookie=cookies.filter(c=>c.name==='np_session').map(c=>c.name+'='+c.value).join(';');assert.ok(oldCookie);
  await page.evaluate(async()=>{await logout();});
  assert.ok((await app.call('auth',{action:'verify'},oldCookie)).status>=400);
  assert.equal(await page.evaluate(()=>Object.keys(localStorage).some(k=>/combat_arc|spawn_lab_staff/.test(k))),false);
  const adminPage=await browser.newPage({viewport:{width:1440,height:1000}});adminPage.on('pageerror',e=>errors.push(e.stack||e.message));await adminPage.route('https://**/*',route=>route.abort());
  const adminCookie=await app.cookie('admin');await adminPage.context().addCookies([{name:'np_session',value:adminCookie.slice('np_session='.length),url:app.origin,httpOnly:true,sameSite:'Strict'}]);
  await adminPage.goto(app.origin);await adminPage.waitForFunction(()=>window.CU&&CU.role==='admin');
  const originalAccounts=(await app.read('accounts')).value.map(a=>({id:a.id,pass:a.pass,role:a.role}));
  adminPage.on('dialog',dialog=>dialog.accept());
  await adminPage.evaluate(()=>{window.__importNotices=[];const previous=notif;window.notif=function(message,type){__importNotices.push({message,type});return previous.apply(this,arguments);};importDB({files:[new File([JSON.stringify({version:1,accounts:[{id:'admin',pseudo:'Admin',role:'joueur'}],players:gp()})],'fixture.json',{type:'application/json'})],value:''});});
  await adminPage.waitForFunction(()=>__importNotices.some(n=>n.message.startsWith('Import enregistré')));
  assert.deepEqual((await app.read('accounts')).value.map(a=>({id:a.id,pass:a.pass,role:a.role})),originalAccounts);
  observations.push('Real import keeps existing passwords and roles even when file contains accounts');
  await adminPage.locator('#dd-staff-btn').click();
  await adminPage.locator('#dd-staff-menu button').filter({hasText:'Administration'}).click();
  await adminPage.locator('#np-admin-dashboard-overview').waitFor({state:'visible'});
  await adminPage.waitForTimeout(1200);
  const dashboardMutations=await adminPage.evaluate(()=>{const observer=new MutationObserver(()=>{});observer.observe(document.getElementById('p-admin-dashboard-c'),{subtree:true,childList:true,attributes:true});npDashboardPolish.refresh();npDashboardPolish.refresh();const count=observer.takeRecords().length;observer.disconnect();return count;});
  assert.equal(dashboardMutations,0,'Refreshing an unchanged admin dashboard must not restart its mutation observer');
  observations.push('Admin overview opens without runtime errors and unchanged refreshes do not rebuild its DOM');
  await adminPage.close();
  assert.deepEqual(errors,[]);assert.deepEqual(app.errors,[]);
  observations.push('Server logout revokes session; no browser/runtime errors in covered flows');
  fs.writeFileSync(path.join(output,'results.json'),JSON.stringify({observations,requests:app.requests,errors},null,2));
  console.log(observations.map(s=>'OK '+s).join('\n'));
 }finally{if(browser)await browser.close();await app.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
